package com.example.demo.service;

import com.example.demo.Model.Attendance;
import com.example.demo.Model.Student;
import com.example.demo.exception.ResourceNotFoundException;
import com.example.demo.repository.AttendanceRepository;
import com.example.demo.repository.StudentRepository;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.stereotype.Service;

import java.io.PrintWriter;
import java.util.List;

@Service
public class ReportServiceImpl implements ReportService {

    private final AttendanceRepository attendanceRepository;
    private final StudentRepository studentRepository;
    private final TeacherClassService teacherClassService;

    public ReportServiceImpl(AttendanceRepository attendanceRepository,
                             StudentRepository studentRepository,
                             TeacherClassService teacherClassService) {
        this.attendanceRepository = attendanceRepository;
        this.studentRepository = studentRepository;
        this.teacherClassService = teacherClassService;
    }

    // -------- CSV --------
    @Override
    public void exportCSV(String studentId, String teacherId, String course,
                          Integer semester, HttpServletResponse response) throws Exception {

        Student student = resolveStudent(studentId, teacherId, course, semester);
        List<Attendance> records = resolveRecords(studentId, teacherId, course, semester);
        String studentName = student.getName();
        long total   = records.size();
        long present = records.stream()
                .filter(a -> "Present".equalsIgnoreCase(a.getStatus())).count();
        double percentage = (present * 100.0) / total;

        // Tell browser this is a downloadable CSV file
        response.setContentType("text/csv");
        response.setHeader("Content-Disposition",
                "attachment; filename=attendance_" + studentId + ".csv");

        PrintWriter writer = response.getWriter();

        // Summary header
        writer.println("Attendance Summary Report");
        writer.println("Student ID," + studentId);
        writer.println("Student Name," + studentName);
        writer.println("Total Classes," + total);
        writer.println("Classes Attended," + present);
        writer.println("Attendance Percentage," + String.format("%.2f", percentage) + "%");
        writer.println();

        // Column headers
        writer.println("Date,Status,Teacher");

        // Records
        for (Attendance a : records) {
            writer.println(a.getDate() + "," + a.getStatus() + "," + a.getTeacherName());
        }

        writer.flush();
    }

    // -------- PDF --------
    @Override
    public void exportPDF(String studentId, String teacherId, String course,
                          Integer semester, HttpServletResponse response) throws Exception {

        Student student = resolveStudent(studentId, teacherId, course, semester);
        List<Attendance> records = resolveRecords(studentId, teacherId, course, semester);
        String studentName = student.getName();
        long total   = records.size();
        long present = records.stream()
                .filter(a -> "Present".equalsIgnoreCase(a.getStatus())).count();
        double percentage = (present * 100.0) / total;
        String risk = percentage >= 75 ? "SAFE" : percentage >= 65 ? "WARNING" : "CRITICAL";

        // Tell browser this is a downloadable PDF file
        response.setContentType("application/pdf");
        response.setHeader("Content-Disposition",
                "attachment; filename=attendance_" + studentId + ".pdf");

        // ---- PDF Structure ----
        Document document = new Document(PageSize.A4, 36, 36, 54, 36);
        PdfWriter.getInstance(document, response.getOutputStream());
        document.open();

        // Fonts
        Font titleFont   = new Font(Font.FontFamily.HELVETICA, 20, Font.BOLD, BaseColor.BLACK);
        Font headerFont  = new Font(Font.FontFamily.HELVETICA, 11, Font.BOLD, BaseColor.WHITE);
        Font labelFont   = new Font(Font.FontFamily.HELVETICA, 10, Font.BOLD, new BaseColor(60, 60, 60));
        Font valueFont   = new Font(Font.FontFamily.HELVETICA, 10, Font.NORMAL, BaseColor.BLACK);
        Font smallFont   = new Font(Font.FontFamily.HELVETICA, 9, Font.NORMAL, new BaseColor(100, 100, 100));

        // Title
        Paragraph title = new Paragraph("Attendance Summary Report", titleFont);
        title.setAlignment(Element.ALIGN_CENTER);
        title.setSpacingAfter(4);
        document.add(title);

        // Subtitle line
        Paragraph subtitle = new Paragraph("Generated by Attendance Monitoring System", smallFont);
        subtitle.setAlignment(Element.ALIGN_CENTER);
        subtitle.setSpacingAfter(20);
        document.add(subtitle);

        // Divider
        document.add(new Chunk(new com.itextpdf.text.pdf.draw.LineSeparator()));
        document.add(Chunk.NEWLINE);

        // Student info table
        PdfPTable infoTable = new PdfPTable(2);
        infoTable.setWidthPercentage(100);
        infoTable.setWidths(new float[]{1, 2});
        infoTable.setSpacingAfter(16);

        addInfoRow(infoTable, "Student ID",    studentId,                          labelFont, valueFont);
        addInfoRow(infoTable, "Student Name",  studentName,                        labelFont, valueFont);
        addInfoRow(infoTable, "Total Classes", String.valueOf(total),               labelFont, valueFont);
        addInfoRow(infoTable, "Present",       String.valueOf(present),             labelFont, valueFont);
        addInfoRow(infoTable, "Absent",        String.valueOf(total - present),     labelFont, valueFont);
        addInfoRow(infoTable, "Percentage",    String.format("%.2f%%", percentage), labelFont, valueFont);
        addInfoRow(infoTable, "Risk Status",   risk,                               labelFont, getRiskFont(risk));

        document.add(infoTable);

        // Section title
        Paragraph recordsTitle = new Paragraph("Attendance Records", labelFont);
        recordsTitle.setSpacingAfter(8);
        document.add(recordsTitle);

        // Records table
        PdfPTable table = new PdfPTable(3);
        table.setWidthPercentage(100);
        table.setWidths(new float[]{2, 2, 2});

        // Table header
        BaseColor headerBg = new BaseColor(52, 52, 80);
        addTableHeader(table, "Date",    headerFont, headerBg);
        addTableHeader(table, "Status",  headerFont, headerBg);
        addTableHeader(table, "Teacher", headerFont, headerBg);

        // Table rows
        boolean alternate = false;
        for (Attendance a : records) {
            BaseColor rowBg = alternate ? new BaseColor(245, 245, 250) : BaseColor.WHITE;
            BaseColor statusColor = "Present".equalsIgnoreCase(a.getStatus())
                    ? new BaseColor(0, 150, 80)
                    : new BaseColor(200, 50, 50);
            Font statusFont = new Font(Font.FontFamily.HELVETICA, 9, Font.BOLD, statusColor);

            addTableCell(table, a.getDate(),        valueFont,  rowBg);
            addTableCell(table, a.getStatus(),      statusFont, rowBg);
            addTableCell(table, a.getTeacherName(), valueFont,  rowBg);
            alternate = !alternate;
        }

        document.add(table);
        document.close();
    }

    // -------- HELPERS --------

    private Student resolveStudent(String studentId, String teacherId,
                                   String course, Integer semester) {
        if (teacherId != null && !teacherId.isBlank()) {
            return teacherClassService.getStudentForTeacherClass(
                    teacherId, studentId, course, semester);
        }

        return studentRepository.findByRollNumber(studentId)
                .orElseThrow(() -> new ResourceNotFoundException(
                        "No student found with roll number: " + studentId));
    }

    private List<Attendance> resolveRecords(String studentId, String teacherId,
                                            String course, Integer semester) {
        List<Attendance> records;
        if (teacherId != null && !teacherId.isBlank()) {
            records = attendanceRepository.findByStudentIdAndCourseAndSemesterOrderByDateDesc(
                    studentId, course, semester);
        } else {
            records = attendanceRepository.findByStudentIdOrderByDateDesc(studentId);
        }

        if (records.isEmpty()) {
            throw new ResourceNotFoundException(
                    "No attendance records found for student: " + studentId);
        }

        return records;
    }

    private void addInfoRow(PdfPTable table, String label, String value,
                            Font labelFont, Font valueFont) {
        PdfPCell labelCell = new PdfPCell(new Phrase(label, labelFont));
        labelCell.setBorder(Rectangle.BOTTOM);
        labelCell.setPadding(6);
        labelCell.setBackgroundColor(new BaseColor(248, 248, 252));

        PdfPCell valueCell = new PdfPCell(new Phrase(value, valueFont));
        valueCell.setBorder(Rectangle.BOTTOM);
        valueCell.setPadding(6);

        table.addCell(labelCell);
        table.addCell(valueCell);
    }

    private void addTableHeader(PdfPTable table, String text,
                                Font font, BaseColor bg) {
        PdfPCell cell = new PdfPCell(new Phrase(text, font));
        cell.setBackgroundColor(bg);
        cell.setPadding(8);
        cell.setBorder(Rectangle.NO_BORDER);
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(cell);
    }

    private void addTableCell(PdfPTable table, String text,
                              Font font, BaseColor bg) {
        PdfPCell cell = new PdfPCell(new Phrase(text, font));
        cell.setBackgroundColor(bg);
        cell.setPadding(7);
        cell.setBorder(Rectangle.BOTTOM);
        cell.setBorderColor(new BaseColor(220, 220, 230));
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(cell);
    }

    private Font getRiskFont(String risk) {
        BaseColor color = risk.equals("SAFE") ? new BaseColor(0, 150, 80)
                : risk.equals("WARNING") ? new BaseColor(200, 140, 0)
                : new BaseColor(200, 50, 50);
        return new Font(Font.FontFamily.HELVETICA, 10, Font.BOLD, color);
    }
}
